<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Assignment extends Model
{
    protected $fillable = [
        'top_heading',
        'top_content',
        'main_extra_content',
        'choose1_heading',
        'choose1_content',
        'choose2_heading',
        'choose2_content',
        'we_are_best',
        'we_are_best_btn',
        'guarantee_heading',
        'guarantee1_heading',
        'guarantee1_content',
        'guarantee2_heading',
        'guarantee2_content',
        'guarantee3_heading',
        'guarantee3_content',
        'guarantee4_heading',
        'guarantee4_content',
        'guarantee5_heading',
        'guarantee5_content',
        'guarantee6_heading',
        'guarantee6_content',
        'guarantee7_heading',
        'guarantee7_content',
        'guarantee8_heading',
        'guarantee8_content',
        'guarantee9_heading',
        'guarantee9_content',
        'guarantee10_heading',
        'guarantee10_content',
        'guarantee11_heading',
        'guarantee11_content',
        'guarantee12_heading',
        'guarantee12_content',
        'guarantee13_heading',
        'guarantee13_content',
        'features_heading',
        'features',
        'features_btn',
        'expert_heading',
        'expert_content',
        'work_heading',
        'work_step1_heading',
        'work_step1_content',
        'work_step2_heading',
        'work_step2_content',
        'work_step3_heading',
        'work_step3_content',
        'work_step4_heading',
        'work_step4_content',
        'work_btn',
        'assignment_type',
        'assignment_content',
        'subject_heading',
        'subject_sub_heading',
        'subject_btn',
        'past_work_heading',
        'past_work_content',
        'last_heading',
        'last_btn_text',
    ];
    public static function form_elements()
    {
        return [
            'top_heading' => 'input',
            'top_content' => 'input',
            'main_extra_content' => 'textarea',
            'choose1_heading' => 'input',
            'choose1_content' => 'textarea',
            'choose2_heading' => 'input',
            'choose2_content' => 'textarea',
            'we_are_best' => 'textarea',
            'we_are_best_btn' => 'input',
            'guarantee_heading' => 'input',
            'guarantee1_heading' => 'input',
            'guarantee1_content' => 'textarea',
            'guarantee2_heading' => 'input',
            'guarantee2_content' => 'textarea',
            'guarantee3_heading' => 'input',
            'guarantee3_content' => 'textarea',
            'guarantee4_heading' => 'input',
            'guarantee4_content' => 'textarea',
            'guarantee5_heading' => 'input',
            'guarantee5_content' => 'textarea',
            'guarantee6_heading' => 'input',
            'guarantee6_content' => 'textarea',
            'guarantee7_heading' => 'input',
            'guarantee7_content' => 'textarea',
            'guarantee8_heading' => 'input',
            'guarantee8_content' => 'textarea',
            'guarantee9_heading' => 'input',
            'guarantee9_content' => 'textarea',
            'guarantee10_heading' => 'input',
            'guarantee10_content' => 'textarea',
            'guarantee11_heading' => 'input',
            'guarantee11_content' => 'textarea',
            'guarantee12_heading' => 'input',
            'guarantee12_content' => 'textarea',
            'guarantee13_heading' => 'input',
            'guarantee13_content' => 'textarea',
            'features_heading' => 'input',
            'features' => 'textarea',
            'features_btn' => 'input',
            'expert_heading' => 'input',
            'expert_content' => 'textarea',
            'work_heading' => 'input',
            'work_step1_heading' => 'input',
            'work_step1_content' => 'textarea',
            'work_step2_heading' => 'input',
            'work_step2_content' => 'textarea',
            'work_step3_heading' => 'input',
            'work_step3_content' => 'textarea',
            'work_step4_heading' => 'input',
            'work_step4_content' => 'textarea',
            'work_btn' => 'input',
            'assignment_type' => 'input',
            'assignment_content' => 'textarea',
            'work_btn' => 'input',
            'subject_heading' => 'input',
            'subject_sub_heading' => 'input',
            'subject_btn' => 'input',
            'past_work_heading' => 'input',
            'past_work_content' => 'textarea',
            'last_heading' => 'input',
            'last_btn_text' => 'input',
        ];
    }
}
