<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class AssignmentPage extends Model
{
    protected $fillable = [
        'name',
        'slug',
        'top_heading',
        'top_content',
        'main_content',
        'main_extra_content',
        'quality_cta_btn',
        'qualtity_heading',
        'qualtity_content',
        'qualtity_heading_1',
        'qualtity_about_1',
        'qualtity_heading_2',
        'qualtity_about_2',
        'qualtity_heading_3',
        'qualtity_about_3',
        'qualtity_heading_4',
        'qualtity_about_4',
        'qualtity_heading_5',
        'qualtity_about_5',
        'qualtity_heading_6',
        'qualtity_about_6',
        'qualtity_heading_7',
        'qualtity_about_7',
        'how_work_heading',
        'how_work_content',
        'how_work_step_1',
        'how_work_step_1_process',
        'how_work_step_2',
        'how_work_step_2_process',
        'how_work_step_3',
        'how_work_step_3_process',
        'how_work_step_4',
        'how_work_step_4_process',
        'work_cta_btn',
        'subject_specialist_heading',
        'subject_specialist_content',
        'subject_area_heading',
        'subject_area_content',
        'subject_area_btn',
        'subject_service_heading',
        'subject_service_content',
        'subject_sample_heading',
        'subject_sample_content',
        'subject_faq_heading',
        'subject_cta_btn',
        'academic_service_heading',
        'academic_service_about',
        'academic_service_1_heading',
        'academic_service_1_about',
        'academic_service_2_heading',
        'academic_service_2_about',
        'academic_service_3_heading',
        'academic_service_3_about',
        'subject_testimonial_heading',
        'subject_testimonial_about',
        'cta_btn_heading',
        'cta_btn_content',
    ];
    public static function form_elements()
    {
        return [
            'name' => 'input',
            // 'slug' => 'input',
            'top_heading' => 'input',
            'top_content' => 'input',
            'main_content' => 'textarea',
            'main_extra_content' => 'textarea',
            'qualtity_heading' => 'input',
            'qualtity_content' => 'textarea',
            'qualtity_heading_1' => 'input',
            'qualtity_about_1' => 'textarea',
            'qualtity_heading_2' => 'input',
            'qualtity_about_2' => 'textarea',
            'qualtity_heading_3' => 'input',
            'qualtity_about_3' => 'textarea',
            'qualtity_heading_4' => 'input',
            'qualtity_about_4' => 'textarea',
            'qualtity_heading_5' => 'input',
            'qualtity_about_5' => 'textarea',
            'qualtity_heading_6' => 'input',
            'qualtity_about_6' => 'textarea',
            'qualtity_heading_7' => 'input',
            'qualtity_about_7' => 'textarea',
            'quality_cta_btn' => 'input',
            'how_work_heading' => 'input',
            'how_work_content' => 'textarea',
            'how_work_step_1' => 'input',
            'how_work_step_1_process' => 'textarea',
            'how_work_step_2' => 'input',
            'how_work_step_2_process' => 'textarea',
            'how_work_step_3' => 'input',
            'how_work_step_3_process' => 'textarea',
            'how_work_step_4' => 'input',
            'how_work_step_4_process' => 'textarea',
            'work_cta_btn' => 'input',
            'subject_specialist_heading' => 'input',
            'subject_specialist_content' => 'textarea',
            'subject_area_heading' => 'input',
            'subject_area_content' => 'textarea',
            'subject_area_btn' => 'input',
            'subject_service_heading' => 'input',
            'subject_service_content' => 'textarea',
            'subject_sample_heading' => 'input',
            'subject_sample_content' => 'textarea',
            'subject_faq_heading' => 'input',
            'subject_cta_btn' => 'input',
            'academic_service_heading' => 'input',
            'academic_service_about' => 'textarea',
            'academic_service_1_heading' => 'input',
            'academic_service_1_about' => 'textarea',
            'academic_service_2_heading' => 'input',
            'academic_service_2_about' => 'textarea',
            'academic_service_3_heading' => 'input',
            'academic_service_3_about' => 'textarea',
            'subject_testimonial_heading' => 'input',
            'subject_testimonial_about' => 'textarea',
            'cta_btn_heading' => 'input',
            'cta_btn_content' => 'input',
        ];
    }
}
