<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class EssayWriting extends Model
{
    protected $fillable = [
        'top_heading',
        'top_content',
        'section_content',
        'section1_heading',
        'section1_content',
        'choose1_heading',
        'choose1_content',
        'choose2_heading',
        'choose2_content',
        'choose3_heading',
        'choose3_content',
        'choose4_heading',
        'choose4_content',
        'choose5_heading',
        'choose5_content',
        'choose6_heading',
        'choose6_content',
        'section_btn',
        'work_heading',
        'work_sub_heading',
        'work_step1_heading',
        'work_step1_content',
        'work_step2_heading',
        'work_step2_content',
        'work_step3_heading',
        'work_step3_content',
        'work_step4_heading',
        'work_step4_content',
        'work_btn',
        'guarantee_heading',
        'guarantee1_heading',
        'guarantee2_heading',
        'guarantee3_heading',
        'guarantee4_heading',
        'guarantee5_heading',
        'guarantee6_heading',
        'expert_heading',
        'expert_content',
        'essay_type',
        'essay_type_content',
        'essay1',
        'essay2',
        'essay3',
        'essay4',
        'essay5',
        'essay6',
        'essay7',
        'essay8',
        'essay9',
        'essay10',
        'essay11',
        'essay12',
        'essay13',
        'essay14',
        'essay15',
        'essay16',
        'essay17',
        'essay18',
        'essay_btn',
        'sample_work_heading',
        'faqs_heading',
        'last_heading',
        'last_btn_text',
    ];
    public static function form_elements()
    {
        return [
            'top_heading' => 'input',
            'top_content' => 'input',
            'section_content' => 'textarea',
            'section1_heading' => 'input',
            'section1_content' => 'textarea',
            'choose1_heading' => 'input',
            'choose1_content' => 'textarea',
            'choose2_heading' => 'input',
            'choose2_content' => 'textarea',
            'choose3_heading' => 'input',
            'choose3_content' => 'textarea',
            'choose4_heading' => 'input',
            'choose4_content' => 'textarea',
            'choose5_heading' => 'input',
            'choose5_content' => 'textarea',
            'choose6_heading' => 'input',
            'choose6_content' => 'textarea',
            'section_btn' => 'input',
            'work_heading' => 'input',
            'work_sub_heading' => 'input',
            'work_step1_heading' => 'input',
            'work_step1_content' => 'textarea',
            'work_step2_heading' => 'input',
            'work_step2_content' => 'textarea',
            'work_step3_heading' => 'input',
            'work_step3_content' => 'textarea',
            'work_step4_heading' => 'input',
            'work_step4_content' => 'textarea',
            'work_btn' => 'input',
            'guarantee_heading' => 'input',
            'guarantee1_heading' => 'input',
            'guarantee2_heading' => 'input',
            'guarantee3_heading' => 'input',
            'guarantee4_heading' => 'input',
            'guarantee5_heading' => 'input',
            'guarantee6_heading' => 'input',
            'expert_heading' => 'input',
            'expert_content' => 'textarea',
            'essay_type' => 'input',
            'essay_type_content' => 'textarea',
            'essay1' => 'input',
            'essay2' => 'input',
            'essay3' => 'input',
            'essay4' => 'input',
            'essay5' => 'input',
            'essay6' => 'input',
            'essay7' => 'input',
            'essay8' => 'input',
            'essay9' => 'input',
            'essay10' => 'input',
            'essay11' => 'input',
            'essay12' => 'input',
            'essay13' => 'input',
            'essay14' => 'input',
            'essay15' => 'input',
            'essay16' => 'input',
            'essay17' => 'input',
            'essay18' => 'input',
            'essay_btn' => 'input',
            'sample_work_heading' => 'input',
            'faqs_heading' => 'input',
            'last_heading' => 'input',
            'last_btn_text' => 'input',
        ];
    }
}
