<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class HomeWork extends Model
{
    protected $fillable = [
        'top_heading',
        'top_content',
        'section1_heading',
        'section1_content',
        'choose1_heading',
        'choose1_content',
        'choose2_heading',
        'choose2_content',
        'choose3_heading',
        'choose3_content',
        'choose4_heading',
        'choose4_content',
        'choose_btn_text',
        'guarantee_heading',
        'guarantee1_heading',
        'guarantee1_content',
        'guarantee2_heading',
        'guarantee2_content',
        'guarantee3_heading',
        'guarantee3_content',
        'guarantee4_heading',
        'guarantee4_content',
        'guarantee5_heading',
        'guarantee5_content',
        'guarantee6_heading',
        'guarantee6_content',
        'guarantee7_heading',
        'service_heading',
        'service_content',
        'service1_heading',
        'service1_content',
        'service2_heading',
        'service2_content',
        'service3_heading',
        'service3_content',
        'service4_heading',
        'service4_content',
        'service_btn_text',
        'expert_heading',
        'expert_content',
        'work_heading',
        'work_content',
        'work_step1_heading',
        'work_step1_content',
        'work_step2_heading',
        'work_step2_content',
        'work_step3_heading',
        'work_step3_content',
        'work_step4_heading',
        'work_step4_content',
        'subject_heading',
        'homework_heading',
        'homework_content',
        'homework1_heading',
        'homework1_content',
        'homework2_heading',
        'homework2_content',
        'homework3_heading',
        'homework3_content',
        'homework4_heading',
        'homework4_content',
        'homework5_heading',
        'homework5_content',
        'homework6_heading',
        'homework6_content',
        'past_work_heading',
        'past_work_content',
        'past_work_cta',
        'testimonial_heading',
        'last_heading',
        'last_btn_text',
    ];

    public static function form_elements()
    {
        return [
            'top_heading' => 'input',
            'top_content' => 'input',
            'section1_heading' => 'input',
            'section1_content' => 'input',
            'choose1_heading' => 'input',
            'choose1_content' => 'textarea',
            'choose2_heading' => 'input',
            'choose2_content' => 'textarea',
            'choose3_heading' => 'input',
            'choose3_content' => 'textarea',
            'choose4_heading' => 'input',
            'choose4_content' => 'textarea',
            'choose_btn_text' => 'input',
            'guarantee_heading' => 'input',
            'guarantee1_heading' => 'input',
            'guarantee1_content' => 'textarea',
            'guarantee2_heading' => 'input',
            'guarantee2_content' => 'textarea',
            'guarantee3_heading' => 'input',
            'guarantee3_content' => 'textarea',
            'guarantee4_heading' => 'input',
            'guarantee4_content' => 'textarea',
            'guarantee5_heading' => 'input',
            'guarantee5_content' => 'textarea',
            'guarantee6_heading' => 'input',
            'guarantee6_content' => 'textarea',
            // 'guarantee7_heading' => 'input',
            'service_heading' => 'input',
            'service_content' => 'textarea',
            'service1_heading' => 'input',
            'service1_content' => 'textarea',
            'service2_heading' => 'input',
            'service2_content' => 'textarea',
            'service3_heading' => 'input',
            'service3_content' => 'textarea',
            'service4_heading' => 'input',
            'service4_content' => 'textarea',
            'service_btn_text' => 'input',
            'expert_heading' => 'input',
            'expert_content' => 'textarea',
            'work_heading' => 'input',
            'work_content' => 'textarea',
            'work_step1_heading' => 'input',
            'work_step1_content' => 'textarea',
            'work_step2_heading' => 'input',
            'work_step2_content' => 'textarea',
            'work_step3_heading' => 'input',
            'work_step3_content' => 'textarea',
            'work_step4_heading' => 'input',
            'work_step4_content' => 'textarea',
            'subject_heading' => 'input',
            'homework_heading' => 'input',
            'homework_content' => 'textarea',
            'homework1_heading' => 'input',
            'homework1_content' => 'textarea',
            'homework2_heading' => 'input',
            'homework2_content' => 'textarea',
            'homework3_heading' => 'input',
            'homework3_content' => 'textarea',
            'homework4_heading' => 'input',
            'homework4_content' => 'textarea',
            'homework5_heading' => 'input',
            'homework5_content' => 'textarea',
            'homework6_heading' => 'input',
            'homework6_content' => 'textarea',
            'past_work_heading' => 'input',
            'past_work_content' => 'textarea',
            'past_work_cta' => 'input',
            'testimonial_heading' => 'input',
            'last_heading' => 'input',
            'last_btn_text' => 'input',
        ];
    }
}
